### PR TITLE
Document fragmentize behavior of magic comments

### PR DESCRIPTION
**Pull request by lamBOOO**
- Also Insert hint for premium API, that magic comments can be used to split larger files in multiple fragments

I hope that this is the right way to contribute docs. I wasn't able to locally host the documenation since I got a problem running `docker compose up` and I have never used the Jekyll SSG 🤔

### CODE REVIEW

**Comment by spitzerd** [comment]
I don't know how to build locally either. 
Maybe you can link https://languagetool.org/http-api/ so the readers can check the current API limits.

Overall, your PR looks fine.

**Comment by lamBOOO** [comment]
If the Github CI runs though, maybe we can use https://github.com/nektos/act to run the CI locally and "learn", how to build the documentation and then construct proper `Dockerfile`s for reproduction.

**Comment by spitzerd** [comment]
Creating a dockerfile based on CI.yml sounds good. Feel free to submit another pull request with a dockerfile.

**Comment by lamBOOO** [comment]
How do you actually trigger the CI? 
I'm confused since I don't see any runs for the 2 `yml`-configs.. 🤔
- https://github.com/ltex-plus/ltex-plus/actions/workflows/ci.yml
- https://github.com/ltex-plus/ltex-plus/actions/workflows/update-gh-pages.yml

**Comment by lamBOOO** [comment]
Do you go to the latest `pages build and deployment` run and simply click "rerun all jobs" there?

**Comment by spitzerd** [comment]
Those two yml files you mentioned are not in use. 

The pages build and deployment run is triggered by Github Pages. You can find a documentation how to run a Github page locally here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll

By the way, I just noticed that there is already a Dockerfile in this repo.

**Comment by lamBOOO** [comment]
Okay, it works for me now locally using Docker, see #2. Can you confirm?

**Pull request merged**
